using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Swap.Htmx.Generators;

/// <summary>
/// Source generator that automatically creates SwapViews and SwapElements classes
/// by scanning all .cshtml files in the project at compile time.
/// No attributes required - just add the package and use the generated classes.
/// </summary>
[Generator]
public class AutoScanGenerator : IIncrementalGenerator
{
    // Regex to match id="value" or id='value' in HTML/Razor
    // Skips dynamic IDs like id="@Model.Id"
    private static readonly Regex IdAttributeRegex = new Regex(
        @"id\s*=\s*[""']([^""'@][^""']*)[""']",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect all .cshtml files from AdditionalTexts
        var cshtmlFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".cshtml", StringComparison.OrdinalIgnoreCase))
            .Collect();

        // Get compilation for namespace detection
        var compilationAndFiles = context.CompilationProvider.Combine(cshtmlFiles);

        // Generate source
        context.RegisterSourceOutput(compilationAndFiles, static (spc, source) =>
        {
            var compilation = source.Left;
            var files = source.Right;

            if (files.IsEmpty)
                return;

            var rootNamespace = compilation.AssemblyName ?? "SwapGenerated";

            // Generate SwapViews
            GenerateSwapViews(spc, files, rootNamespace);

            // Generate SwapElements
            GenerateSwapElements(spc, files, rootNamespace);
        });
    }

    private static void GenerateSwapViews(
        SourceProductionContext context,
        System.Collections.Immutable.ImmutableArray<AdditionalText> files,
        string rootNamespace)
    {
        var viewsByFolder = new Dictionary<string, Dictionary<string, ViewInfo>>(StringComparer.OrdinalIgnoreCase);

        foreach (var file in files)
        {
            var path = NormalizePath(file.Path);
            var viewInfo = ParseViewPath(path);
            
            if (viewInfo == null)
                continue;

            if (!viewsByFolder.TryGetValue(viewInfo.Folder, out var viewsDict))
            {
                viewsDict = new Dictionary<string, ViewInfo>(StringComparer.OrdinalIgnoreCase);
                viewsByFolder[viewInfo.Folder] = viewsDict;
            }
            
            // Use relativePath as key to avoid duplicates
            var key = viewInfo.RelativePath;
            if (!viewsDict.ContainsKey(key))
            {
                viewsDict[key] = viewInfo;
            }
        }

        if (viewsByFolder.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Swap.Htmx.Generators - do not edit");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated view path constants from .cshtml files.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class SwapViews");
        sb.AppendLine("    {");

        foreach (var kvp in viewsByFolder.OrderBy(k => k.Key))
        {
            var folder = kvp.Key;
            var views = kvp.Value.Values.OrderBy(v => v.FileName).ToList();
            var className = ToValidClassName(folder);

            sb.AppendLine($"        public static class {className}");
            sb.AppendLine("        {");

            // Track used constant names to avoid duplicates within a class
            var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            
            foreach (var view in views)
            {
                var constantName = ToValidIdentifier(view.FileName);
                
                // If duplicate name in same class, append number
                var finalName = constantName;
                var counter = 2;
                while (usedNames.Contains(finalName))
                {
                    finalName = constantName + counter++;
                }
                usedNames.Add(finalName);
                
                // For partials (starting with _), use just the filename for AlsoUpdate compatibility
                // For full views, use the complete path for SwapView() usage
                var viewValue = view.FileName.StartsWith("_") 
                    ? view.FileName 
                    : view.RelativePath;
                
                sb.AppendLine($"            public const string {finalName} = \"{viewValue}\";");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("SwapViews.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateSwapElements(
        SourceProductionContext context,
        System.Collections.Immutable.ImmutableArray<AdditionalText> files,
        string rootNamespace)
    {
        var allIds = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase); // id -> source file

        foreach (var file in files)
        {
            var content = file.GetText()?.ToString();
            if (string.IsNullOrEmpty(content))
                continue;

            var ids = ExtractIds(content);
            var fileName = Path.GetFileNameWithoutExtension(file.Path);

            foreach (var id in ids)
            {
                if (!allIds.ContainsKey(id))
                {
                    allIds[id] = fileName;
                }
            }
        }

        if (allIds.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Swap.Htmx.Generators - do not edit");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated element ID constants from .cshtml files.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class SwapElements");
        sb.AppendLine("    {");

        foreach (var kvp in allIds.OrderBy(k => k.Key))
        {
            var id = kvp.Key;
            var constantName = ToValidIdentifier(id);
            sb.AppendLine($"        /// <summary>From {kvp.Value}</summary>");
            sb.AppendLine($"        public const string {constantName} = \"{id}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("SwapElements.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static IEnumerable<string> ExtractIds(string content)
    {
        var matches = IdAttributeRegex.Matches(content);
        foreach (Match match in matches)
        {
            if (match.Success && match.Groups.Count > 1)
            {
                var id = match.Groups[1].Value.Trim();

                // Skip empty IDs or IDs that look like Razor expressions
                if (!string.IsNullOrEmpty(id) &&
                    !id.Contains("@") &&
                    !id.Contains("{") &&
                    !id.Contains("}") &&
                    !id.StartsWith("__"))  // Skip framework-generated IDs
                {
                    yield return id;
                }
            }
        }
    }

    private static string NormalizePath(string path)
    {
        return path.Replace('\\', '/');
    }

    private static ViewInfo? ParseViewPath(string fullPath)
    {
        // Handle patterns:
        // - Views/Home/Index.cshtml -> folder="Home", path="~/Views/Home/Index.cshtml"
        // - Views/Shared/_Layout.cshtml -> folder="Shared", path="~/Views/Shared/_Layout.cshtml"
        // - Modules/Notes/Views/Index.cshtml -> folder="Notes", path="~/Modules/Notes/Views/Index.cshtml"
        // - Modules/Notes/Views/_NoteCard.cshtml -> folder="Notes", path="~/Modules/Notes/Views/_NoteCard.cshtml"
        // - Pages/Index.cshtml -> folder="Pages", path="~/Pages/Index.cshtml"

        var parts = fullPath.Split('/');
        var fileName = Path.GetFileNameWithoutExtension(parts[parts.Length - 1]);

        string folder = "Shared";
        string relativePath = "";

        // Find the Views or Pages folder
        int viewsIndex = -1;
        int modulesIndex = -1;
        
        for (int i = 0; i < parts.Length; i++)
        {
            if (parts[i].Equals("Modules", StringComparison.OrdinalIgnoreCase))
            {
                modulesIndex = i;
            }
            if (parts[i].Equals("Views", StringComparison.OrdinalIgnoreCase))
            {
                viewsIndex = i;
            }
            if (parts[i].Equals("Pages", StringComparison.OrdinalIgnoreCase))
            {
                viewsIndex = i;
                folder = "Pages";
            }
        }

        if (viewsIndex >= 0)
        {
            // If we have a Modules folder before Views, use the module name as folder
            if (modulesIndex >= 0 && modulesIndex < viewsIndex && modulesIndex + 1 < viewsIndex)
            {
                folder = parts[modulesIndex + 1]; // e.g., "Notes" from "Modules/Notes/Views"
                
                // Build relative path from Modules folder
                var pathParts = new List<string>();
                for (int j = modulesIndex; j < parts.Length; j++)
                {
                    pathParts.Add(parts[j]);
                }
                relativePath = "~/" + string.Join("/", pathParts);
            }
            else
            {
                // Standard Views folder - use subfolder as the group
                if (viewsIndex + 1 < parts.Length - 1)
                {
                    folder = parts[viewsIndex + 1]; // e.g., "Home" from "Views/Home/Index.cshtml"
                }
                
                // Build relative path from Views/Pages folder
                var pathParts = new List<string>();
                for (int j = viewsIndex; j < parts.Length; j++)
                {
                    pathParts.Add(parts[j]);
                }
                relativePath = "~/" + string.Join("/", pathParts);
            }
        }
        else
        {
            // No Views/Pages folder found, use parent folder
            if (parts.Length >= 2)
            {
                folder = parts[parts.Length - 2];
            }
            // Take last 3 parts for relative path
            var lastParts = new List<string>();
            int startIdx = Math.Max(0, parts.Length - 3);
            for (int j = startIdx; j < parts.Length; j++)
            {
                lastParts.Add(parts[j]);
            }
            relativePath = "~/" + string.Join("/", lastParts);
        }

        return new ViewInfo(folder, fileName, relativePath);
    }

    private static string ToValidClassName(string name)
    {
        if (string.IsNullOrEmpty(name)) return "Root";

        var sb = new StringBuilder();

        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(sb.Length == 0 ? char.ToUpper(c) : c);
            }
            else if (c == '_' || c == '-')
            {
                // Skip but capitalize next
                continue;
            }
        }

        var result = sb.ToString();
        
        // Ensure it starts with a letter
        if (result.Length > 0 && char.IsDigit(result[0]))
        {
            result = "_" + result;
        }

        return string.IsNullOrEmpty(result) ? "Root" : result;
    }

    private static string ToValidIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "_";

        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in name)
        {
            if (c == '-' || c == '_' || c == '.')
            {
                capitalizeNext = true;
                continue;
            }

            if (char.IsLetterOrDigit(c))
            {
                if (sb.Length == 0 && char.IsDigit(c))
                {
                    sb.Append('_');
                }

                sb.Append(capitalizeNext ? char.ToUpper(c) : c);
                capitalizeNext = false;
            }
        }

        return sb.Length > 0 ? sb.ToString() : "_";
    }

    private class ViewInfo
    {
        public string Folder { get; }
        public string FileName { get; }
        public string RelativePath { get; }

        public ViewInfo(string folder, string fileName, string relativePath)
        {
            Folder = folder;
            FileName = fileName;
            RelativePath = relativePath;
        }
    }
}
