using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Swap.Htmx.Generators;

/// <summary>
/// Source generator that automatically creates SwapViews and SwapElements classes
/// by scanning all .cshtml files in the project at compile time.
/// No attributes required - just add the package and use the generated classes.
/// 
/// SwapViews are grouped by controller folder for intuitive usage:
///   SwapViews.TenantsManagement.Index
///   SwapViews.TenantsManagement._TenantList
///   SwapViews.Shared._Layout
/// 
/// SwapElements contains all static element IDs found in views.
/// </summary>
[Generator]
public class AutoScanGenerator : IIncrementalGenerator
{
    // Regex to match id="value" or id='value' in HTML/Razor
    // Skips dynamic IDs like id="@Model.Id"
    private static readonly Regex IdAttributeRegex = new Regex(
        @"id\s*=\s*[""']([^""'@][^""']*)[""']",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect all .cshtml files from AdditionalTexts
        var cshtmlFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".cshtml", StringComparison.OrdinalIgnoreCase))
            .Collect();

        // Get compilation for namespace detection
        var compilationAndFiles = context.CompilationProvider.Combine(cshtmlFiles);

        // Generate source
        context.RegisterSourceOutput(compilationAndFiles, static (spc, source) =>
        {
            var compilation = source.Left;
            var files = source.Right;

            if (files.IsEmpty)
                return;

            var rootNamespace = compilation.AssemblyName ?? "SwapGenerated";

            // Generate SwapViews
            GenerateSwapViews(spc, files, rootNamespace);

            // Generate SwapElements
            GenerateSwapElements(spc, files, rootNamespace);
        });
    }

    private static void GenerateSwapViews(
        SourceProductionContext context,
        System.Collections.Immutable.ImmutableArray<AdditionalText> files,
        string rootNamespace)
    {
        // Group views by controller folder
        // Key: controller folder name (e.g., "TenantsManagement", "Shared", "Home")
        // Value: Dictionary of view filename -> ViewInfo
        var viewsByController = new Dictionary<string, Dictionary<string, ViewInfo>>(StringComparer.OrdinalIgnoreCase);

        foreach (var file in files)
        {
            var path = NormalizePath(file.Path);
            var viewInfo = ParseViewPath(path);
            
            if (viewInfo == null)
                continue;

            if (!viewsByController.TryGetValue(viewInfo.ControllerFolder, out var viewsDict))
            {
                viewsDict = new Dictionary<string, ViewInfo>(StringComparer.OrdinalIgnoreCase);
                viewsByController[viewInfo.ControllerFolder] = viewsDict;
            }
            
            // Use filename as key - duplicates within same folder are errors anyway
            if (!viewsDict.ContainsKey(viewInfo.FileName))
            {
                viewsDict[viewInfo.FileName] = viewInfo;
            }
        }

        if (viewsByController.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Swap.Htmx.Generators - do not edit");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated view constants grouped by controller folder.");
        sb.AppendLine("    /// Usage: SwapViews.TenantsManagement._TenantList");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class SwapViews");
        sb.AppendLine("    {");

        foreach (var kvp in viewsByController.OrderBy(k => k.Key))
        {
            var controllerFolder = kvp.Key;
            var views = kvp.Value.Values.OrderBy(v => v.FileName).ToList();
            var className = ToValidClassName(controllerFolder);

            sb.AppendLine($"        /// <summary>Views for {controllerFolder}</summary>");
            sb.AppendLine($"        public static class {className}");
            sb.AppendLine("        {");

            foreach (var view in views)
            {
                // Keep the filename as-is (including underscore for partials)
                // This prevents clashes between _TenantList and TenantList
                var constantName = ToValidIdentifier(view.FileName);
                
                // All views use short names - Razor resolves them relative to controller
                sb.AppendLine($"            public const string {constantName} = \"{view.FileName}\";");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("SwapViews.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateSwapElements(
        SourceProductionContext context,
        System.Collections.Immutable.ImmutableArray<AdditionalText> files,
        string rootNamespace)
    {
        var allIds = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase); // id -> source file

        foreach (var file in files)
        {
            var content = file.GetText()?.ToString();
            if (string.IsNullOrEmpty(content))
                continue;

            var ids = ExtractIds(content);
            var fileName = Path.GetFileNameWithoutExtension(file.Path);

            foreach (var id in ids)
            {
                if (!allIds.ContainsKey(id))
                {
                    allIds[id] = fileName;
                }
            }
        }

        if (allIds.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Swap.Htmx.Generators - do not edit");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated element ID constants from .cshtml files.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class SwapElements");
        sb.AppendLine("    {");

        foreach (var kvp in allIds.OrderBy(k => k.Key))
        {
            var id = kvp.Key;
            var constantName = ToValidIdentifier(id);
            sb.AppendLine($"        /// <summary>From {kvp.Value}</summary>");
            sb.AppendLine($"        public const string {constantName} = \"{id}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("SwapElements.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static IEnumerable<string> ExtractIds(string content)
    {
        var matches = IdAttributeRegex.Matches(content);
        foreach (Match match in matches)
        {
            if (match.Success && match.Groups.Count > 1)
            {
                var id = match.Groups[1].Value.Trim();

                // Skip empty IDs or IDs that look like Razor expressions
                if (string.IsNullOrEmpty(id))
                    continue;
                    
                // Skip Razor expressions
                if (id.Contains("@") || id.Contains("{") || id.Contains("}"))
                    continue;
                    
                // Skip framework-generated IDs
                if (id.StartsWith("__"))
                    continue;
                    
                // Skip numeric-only IDs (noise like "3", "4", "123")
                if (id.All(char.IsDigit))
                    continue;
                    
                // Skip single character IDs (noise)
                if (id.Length == 1)
                    continue;

                yield return id;
            }
        }
    }

    private static string NormalizePath(string path)
    {
        return path.Replace('\\', '/');
    }

    private static ViewInfo? ParseViewPath(string fullPath)
    {
        // Parse view paths to extract controller folder and filename
        // 
        // Standard MVC:
        //   Views/Home/Index.cshtml -> ControllerFolder="Home", FileName="Index"
        //   Views/Shared/_Layout.cshtml -> ControllerFolder="Shared", FileName="_Layout"
        //
        // Modular Monolith:
        //   Modules/SuperAdmin/Views/TenantsManagement/Index.cshtml -> ControllerFolder="TenantsManagement"
        //   Modules/SuperAdmin/Views/Shared/_Layout.cshtml -> ControllerFolder="Shared"
        //
        // Areas:
        //   Areas/Admin/Views/Home/Index.cshtml -> ControllerFolder="Admin_Home" (nested)
        //
        // Razor Pages:
        //   Pages/Account/Login.cshtml -> ControllerFolder="Account", FileName="Login"
        //   Pages/Index.cshtml -> ControllerFolder="Pages", FileName="Index"
        //
        // Components:
        //   Components/WeatherWidget/Default.cshtml -> ControllerFolder="WeatherWidget"

        var parts = fullPath.Split('/');
        var fileNameWithExt = parts[parts.Length - 1];
        var fileName = Path.GetFileNameWithoutExtension(fileNameWithExt);

        // Skip special Razor files
        if (fileName == "_ViewStart" || fileName == "_ViewImports")
            return null;

        string controllerFolder = "Root";

        // Find key folder markers
        int viewsIndex = -1;
        int pagesIndex = -1;
        int areasIndex = -1;
        int componentsIndex = -1;
        
        for (int i = 0; i < parts.Length; i++)
        {
            var part = parts[i];
            if (part.Equals("Views", StringComparison.OrdinalIgnoreCase))
                viewsIndex = i;
            else if (part.Equals("Pages", StringComparison.OrdinalIgnoreCase))
                pagesIndex = i;
            else if (part.Equals("Areas", StringComparison.OrdinalIgnoreCase))
                areasIndex = i;
            else if (part.Equals("Components", StringComparison.OrdinalIgnoreCase))
                componentsIndex = i;
        }

        // Determine controller folder based on structure
        if (viewsIndex >= 0)
        {
            // Standard Views folder structure
            // Views/{ControllerFolder}/{View}.cshtml
            // or Views/{ControllerFolder}/SubFolder/{View}.cshtml (still use ControllerFolder)
            
            if (viewsIndex + 1 < parts.Length - 1)
            {
                // Has a subfolder after Views - that's our controller folder
                controllerFolder = parts[viewsIndex + 1];
                
                // Check for Areas pattern: Areas/{Area}/Views/{Controller}/
                if (areasIndex >= 0 && areasIndex < viewsIndex && areasIndex + 1 < viewsIndex)
                {
                    var areaName = parts[areasIndex + 1];
                    controllerFolder = $"{areaName}_{controllerFolder}";
                }
            }
            else
            {
                // File directly in Views folder (unlikely but handle it)
                controllerFolder = "Root";
            }
        }
        else if (pagesIndex >= 0)
        {
            // Razor Pages structure
            // Pages/{Folder}/{Page}.cshtml -> Folder
            // Pages/{Page}.cshtml -> Pages
            
            if (pagesIndex + 1 < parts.Length - 1)
            {
                controllerFolder = parts[pagesIndex + 1];
            }
            else
            {
                controllerFolder = "Pages";
            }
        }
        else if (componentsIndex >= 0)
        {
            // View Components
            // Components/{ComponentName}/{View}.cshtml
            
            if (componentsIndex + 1 < parts.Length - 1)
            {
                controllerFolder = parts[componentsIndex + 1];
            }
            else
            {
                controllerFolder = "Components";
            }
        }
        else
        {
            // Fallback: use parent folder
            if (parts.Length >= 2)
            {
                controllerFolder = parts[parts.Length - 2];
            }
        }

        return new ViewInfo(controllerFolder, fileName);
    }

    private static string ToValidClassName(string name)
    {
        if (string.IsNullOrEmpty(name)) return "Root";

        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in name)
        {
            if (c == '-' || c == '_' || c == '.')
            {
                capitalizeNext = true;
                continue;
            }

            if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalizeNext ? char.ToUpper(c) : c);
                capitalizeNext = false;
            }
        }

        var result = sb.ToString();
        
        // Ensure it starts with a letter
        if (result.Length > 0 && char.IsDigit(result[0]))
        {
            result = "_" + result;
        }

        return string.IsNullOrEmpty(result) ? "Root" : result;
    }

    private static string ToValidIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "_";

        // Handle underscore prefix for partials - keep it!
        var startsWithUnderscore = name.StartsWith("_");
        
        var sb = new StringBuilder();
        var capitalizeNext = !startsWithUnderscore; // Don't capitalize first char if starts with _

        foreach (var c in name)
        {
            if (c == '-' || c == '.')
            {
                capitalizeNext = true;
                continue;
            }

            if (c == '_')
            {
                // Keep underscores as-is (important for partial naming)
                sb.Append('_');
                capitalizeNext = true;
                continue;
            }

            if (char.IsLetterOrDigit(c))
            {
                if (sb.Length == 0 && char.IsDigit(c))
                {
                    sb.Append('_');
                }

                sb.Append(capitalizeNext ? char.ToUpper(c) : c);
                capitalizeNext = false;
            }
        }

        return sb.Length > 0 ? sb.ToString() : "_";
    }

    private class ViewInfo
    {
        public string ControllerFolder { get; }
        public string FileName { get; }

        public ViewInfo(string controllerFolder, string fileName)
        {
            ControllerFolder = controllerFolder;
            FileName = fileName;
        }
    }
}
