using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Swap.Htmx.Generators
{
    [Generator]
    public class EventSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Filter for classes with the [SwapEventSource] attribute
            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => IsSyntaxTargetForGeneration(s),
                    transform: (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(t => t != null);

            context.RegisterSourceOutput(provider, (spc, source) => Execute(spc, source));
        }

        private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax c && c.AttributeLists.Count > 0;
        }

        private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;

            foreach (var attributeList in classDeclaration.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    // Simple name check first to avoid expensive semantic model lookups if possible
                    var name = attribute.Name.ToString();
                    if (name.Contains("SwapEventSource"))
                    {
                        return classDeclaration;
                    }
                }
            }

            return null;
        }

        private static void Execute(SourceProductionContext context, ClassDeclarationSyntax? classDeclaration)
        {
            if (classDeclaration == null) return;

            // We need to get the constants from the class
            var namespaceName = GetNamespace(classDeclaration);
            var className = classDeclaration.Identifier.Text;
            
            var fields = new List<(string Name, string Value)>();

            foreach (var member in classDeclaration.Members)
            {
                if (member is FieldDeclarationSyntax fieldDeclaration)
                {
                    // Check if const string
                    var isConst = fieldDeclaration.Modifiers.Any(m => m.Text == "const");
                    var isString = fieldDeclaration.Declaration.Type.ToString() == "string";
                    
                    if (isConst && isString)
                    {
                        foreach (var variable in fieldDeclaration.Declaration.Variables)
                        {
                            var name = variable.Identifier.Text;
                            var value = variable.Initializer?.Value.ToString().Trim('"');
                            
                            if (!string.IsNullOrEmpty(value))
                            {
                                fields.Add((name, value!));
                            }
                        }
                    }
                }
            }

            var source = GenerateSource(namespaceName, className, fields);
            context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
        }

        private static string GetNamespace(BaseTypeDeclarationSyntax syntax)
        {
            var potentialNamespaceParent = syntax.Parent;
            while (potentialNamespaceParent != null &&
                   !(potentialNamespaceParent is NamespaceDeclarationSyntax) &&
                   !(potentialNamespaceParent is FileScopedNamespaceDeclarationSyntax))
            {
                potentialNamespaceParent = potentialNamespaceParent.Parent;
            }

            if (potentialNamespaceParent is BaseNamespaceDeclarationSyntax namespaceParent)
            {
                return namespaceParent.Name.ToString();
            }

            return "Global";
        }

        private static string GenerateSource(string namespaceName, string className, List<(string Name, string Value)> fields)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Swap.Htmx.Events;");
            sb.AppendLine();
            
            if (namespaceName != "Global")
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");

            // Build the hierarchy tree
            var root = new Node();
            foreach (var field in fields)
            {
                var parts = field.Value.Split('.');
                var current = root;
                foreach (var part in parts)
                {
                    if (!current.Children.ContainsKey(part))
                    {
                        current.Children[part] = new Node { Name = part };
                    }
                    current = current.Children[part];
                }
                current.FullEventName = field.Value;
            }

            // Generate classes from tree
            GenerateNodes(sb, root, 2);

            sb.AppendLine("    }");

            if (namespaceName != "Global")
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void GenerateNodes(StringBuilder sb, Node node, int indentLevel)
        {
            var indent = new string(' ', indentLevel * 4);

            foreach (var child in node.Children.Values)
            {
                var pascalName = ToPascalCase(child.Name);

                // If this node is a leaf (has a full event name), generate a property
                if (child.FullEventName != null)
                {
                    // If it also has children, we need a class AND a property. 
                    // But usually "user.created" means "created" is the leaf.
                    // If we have "user" and "user.created", "user" is a node and "created" is a child.
                    // If we have "user" as an event AND "user.something", that's tricky.
                    // For now, assume leaves are properties.
                    
                    // However, the structure is usually:
                    // user.created -> User class, Created property.
                    
                    // If the node has children, it's a class.
                    if (child.Children.Count > 0)
                    {
                        sb.AppendLine($"{indent}public static partial class {pascalName}");
                        sb.AppendLine($"{indent}{{");
                        GenerateNodes(sb, child, indentLevel + 1);
                        sb.AppendLine($"{indent}}}");
                    }
                    else
                    {
                        // It's a leaf property
                        sb.AppendLine($"{indent}public static readonly EventKey {pascalName} = new EventKey(\"{child.FullEventName}\");");
                    }
                }
                else
                {
                    // It's just a container node (e.g. "user" in "user.created")
                    sb.AppendLine($"{indent}public static partial class {pascalName}");
                    sb.AppendLine($"{indent}{{");
                    GenerateNodes(sb, child, indentLevel + 1);
                    sb.AppendLine($"{indent}}}");
                }
            }
        }

        private static string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            return char.ToUpper(input[0]) + input.Substring(1);
        }

        private class Node
        {
            public string Name { get; set; } = "";
            public string? FullEventName { get; set; }
            public Dictionary<string, Node> Children { get; } = new Dictionary<string, Node>();
        }
    }
}