namespace NetMX.Ddd.Domain.Events;

/// <summary>
/// Entities that implement this interface can raise domain events.
/// </summary>
public interface IGeneratesDomainEvents
{
    /// <summary>
    /// Gets the collection of domain events generated by this entity.
    /// </summary>
    IReadOnlyCollection<DomainEvent> DomainEvents { get; }

    /// <summary>
    /// Adds a domain event to this entity.
    /// </summary>
    void AddDomainEvent(DomainEvent domainEvent);

    /// <summary>
    /// Clears all domain events from this entity.
    /// </summary>
    void ClearDomainEvents();
}
