// <auto-generated />
using System;
using KanbanApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KanbanApp.Migrations
{
    [DbContext(typeof(KanbanDbContext))]
    partial class KanbanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("KanbanApp.Data.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Track product features and releases",
                            IsArchived = false,
                            Name = "Product Roadmap",
                            Position = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Current sprint tasks",
                            IsArchived = false,
                            Name = "Sprint Planning",
                            Position = 1
                        });
                });

            modelBuilder.Entity("KanbanApp.Data.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListId", "Position");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implement OAuth2 login",
                            ListId = 1,
                            Position = 0,
                            Priority = 2,
                            Title = "User Authentication"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Integrate Stripe payments",
                            ListId = 1,
                            Position = 1,
                            Priority = 1,
                            Title = "Payment Gateway"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Send transactional emails",
                            ListId = 1,
                            Position = 2,
                            Priority = 0,
                            Title = "Email Notifications"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Design EF Core models",
                            ListId = 2,
                            Position = 0,
                            Priority = 2,
                            Title = "Database Schema"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build REST API",
                            ListId = 2,
                            Position = 1,
                            Priority = 2,
                            Title = "API Endpoints"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initialize project with .NET 9",
                            ListId = 3,
                            Position = 0,
                            Priority = 2,
                            Title = "Project Setup"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Setup GitHub Actions",
                            ListId = 3,
                            Position = 1,
                            Priority = 1,
                            Title = "CI/CD Pipeline"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plan next 2 weeks",
                            DueDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListId = 4,
                            Position = 0,
                            Priority = 3,
                            Title = "Sprint Planning Meeting"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fix 401 error on login",
                            ListId = 4,
                            Position = 1,
                            Priority = 3,
                            Title = "Bug Fix: Login Error"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add search functionality",
                            ListId = 5,
                            Position = 0,
                            Priority = 2,
                            Title = "Implement Search"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Review PR #42",
                            ListId = 6,
                            Position = 0,
                            Priority = 1,
                            Title = "Code Review: Auth Module"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deploy latest version",
                            ListId = 7,
                            Position = 0,
                            Priority = 1,
                            Title = "Deploy to Staging"
                        });
                });

            modelBuilder.Entity("KanbanApp.Data.KanbanList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Position");

                    b.ToTable("Lists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardId = 1,
                            IsArchived = false,
                            Name = "Backlog",
                            Position = 0
                        },
                        new
                        {
                            Id = 2,
                            BoardId = 1,
                            IsArchived = false,
                            Name = "In Progress",
                            Position = 1
                        },
                        new
                        {
                            Id = 3,
                            BoardId = 1,
                            IsArchived = false,
                            Name = "Done",
                            Position = 2
                        },
                        new
                        {
                            Id = 4,
                            BoardId = 2,
                            IsArchived = false,
                            Name = "To Do",
                            Position = 0
                        },
                        new
                        {
                            Id = 5,
                            BoardId = 2,
                            IsArchived = false,
                            Name = "Doing",
                            Position = 1
                        },
                        new
                        {
                            Id = 6,
                            BoardId = 2,
                            IsArchived = false,
                            Name = "Review",
                            Position = 2
                        },
                        new
                        {
                            Id = 7,
                            BoardId = 2,
                            IsArchived = false,
                            Name = "Completed",
                            Position = 3
                        });
                });

            modelBuilder.Entity("KanbanApp.Data.Card", b =>
                {
                    b.HasOne("KanbanApp.Data.KanbanList", "List")
                        .WithMany("Cards")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("KanbanApp.Data.KanbanList", b =>
                {
                    b.HasOne("KanbanApp.Data.Board", "Board")
                        .WithMany("Lists")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("KanbanApp.Data.Board", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("KanbanApp.Data.KanbanList", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
