// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlow.Data;

#nullable disable

namespace TaskFlow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("TaskFlow.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("TaskFlow.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "DevOps Team",
                            CompletedAt = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure CI/CD, database, and hosting",
                            Priority = 2,
                            Status = 2,
                            Tags = "",
                            Title = "Set up project infrastructure"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Design Team",
                            CreatedAt = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create mockups for the task management interface",
                            DueDate = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Status = 1,
                            Tags = "",
                            Title = "Design task board UI"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Backend Team",
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add user login and registration features",
                            DueDate = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Status = 0,
                            Tags = "",
                            Title = "Implement authentication"
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = "Documentation Team",
                            CreatedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Document all REST endpoints and data models",
                            DueDate = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 0,
                            Status = 0,
                            Tags = "",
                            Title = "Write API documentation"
                        });
                });

            modelBuilder.Entity("TaskFlow.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsComplete = false,
                            Title = "Welcome to Swap!"
                        },
                        new
                        {
                            Id = 2,
                            IsComplete = false,
                            Title = "Build something amazing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
