-- 20250601_1510_SeedPatientFacilityVisitHistory.sql
-- Seeds data for patient visits across different facilities.

SET search_path TO app, public;

-- Based on the visits seeded in 20250601_1505_SeedPatientVisits.sql
-- Note: This is a simplified way; in a real system, this would likely be updated by triggers on the visits table.

INSERT INTO patient_facility_visits_history (patient_id, facility_id, first_visit_at, last_visit_at) VALUES
((SELECT patient_id FROM patients WHERE force_number = 'PTE10000001'), (SELECT facility_id FROM facilities WHERE short_code = '2MH'), (SELECT MIN(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'PTE10000001') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '2MH')), (SELECT MAX(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'PTE10000001') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '2MH'))),
((SELECT patient_id FROM patients WHERE force_number = 'SGT10000002'), (SELECT facility_id FROM facilities WHERE short_code = '2MH'), (SELECT MIN(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'SGT10000002') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '2MH')), (SELECT MAX(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'SGT10000002') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '2MH'))),
((SELECT patient_id FROM patients WHERE force_number = 'CPL10000003'), (SELECT facility_id FROM facilities WHERE short_code = '2MH'), (SELECT MIN(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'CPL10000003') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '2MH')), (SELECT MAX(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'CPL10000003') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '2MH'))),
((SELECT patient_id FROM patients WHERE force_number = 'SSG10000004'), (SELECT facility_id FROM facilities WHERE short_code = '2MH'), (SELECT MIN(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'SSG10000004') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '2MH')), (SELECT MAX(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'SSG10000004') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '2MH'))),
((SELECT patient_id FROM patients WHERE force_number = 'CPT10000005'), (SELECT facility_id FROM facilities WHERE short_code = '1MH'), (SELECT MIN(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'CPT10000005') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '1MH')), (SELECT MAX(visit_timestamp) FROM visits WHERE patient_id = (SELECT patient_id FROM patients WHERE force_number = 'CPT10000005') AND facility_id = (SELECT facility_id FROM facilities WHERE short_code = '1MH')));